[project]
name = "django-postgres-loader"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Jacob Ayers", email = "jcayers20@gmail.com" },
]
urls = { "Homepage" = "https://github.com/jcayers20/django-postgres-loader" }
keywords = ["django", "postgres", "PostgreSQL", "ETL", "load"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Lanuage :: Python :: 3.14",
]
dependencies = [
    "django>=4.2",
    "jinja2>=3.1",
]

[dependency-groups]
dev = [
    "build>=1.4.0",
    "pandas>=2.3.3",
    "pre-commit>=4.5.1",
    "psycopg2>=2.9.11",
    "pytest>=9.0.2",
    "pytest-cov>=4.0.0",
    "ruff>=0.15.6",
    "sqlfluff>=4.0.4",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

[tool.pytest.ini_options]
addopts = "-v --cov django_postgres_loader --cov-report html"
log_cli = true
log_cli_level = "INFO"
